//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientView.MathProblemService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/StudentWarDataServer")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MathProblemService.ISystemManagementService")]
    public interface ISystemManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemManagementService/GetData", ReplyAction="http://tempuri.org/ISystemManagementService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemManagementService/GetData", ReplyAction="http://tempuri.org/ISystemManagementService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemManagementService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ISystemManagementService/GetDataUsingDataContractResponse")]
        ClientView.MathProblemService.CompositeType GetDataUsingDataContract(ClientView.MathProblemService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemManagementService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ISystemManagementService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ClientView.MathProblemService.CompositeType> GetDataUsingDataContractAsync(ClientView.MathProblemService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemManagementService/InsertMathProblem", ReplyAction="http://tempuri.org/ISystemManagementService/InsertMathProblemResponse")]
        bool InsertMathProblem(string mathProblemJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemManagementService/InsertMathProblem", ReplyAction="http://tempuri.org/ISystemManagementService/InsertMathProblemResponse")]
        System.Threading.Tasks.Task<bool> InsertMathProblemAsync(string mathProblemJson);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISystemManagementServiceChannel : ClientView.MathProblemService.ISystemManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SystemManagementServiceClient : System.ServiceModel.ClientBase<ClientView.MathProblemService.ISystemManagementService>, ClientView.MathProblemService.ISystemManagementService {
        
        public SystemManagementServiceClient() {
        }
        
        public SystemManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SystemManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ClientView.MathProblemService.CompositeType GetDataUsingDataContract(ClientView.MathProblemService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ClientView.MathProblemService.CompositeType> GetDataUsingDataContractAsync(ClientView.MathProblemService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public bool InsertMathProblem(string mathProblemJson) {
            return base.Channel.InsertMathProblem(mathProblemJson);
        }
        
        public System.Threading.Tasks.Task<bool> InsertMathProblemAsync(string mathProblemJson) {
            return base.Channel.InsertMathProblemAsync(mathProblemJson);
        }
    }
}
